"""
Pydantic models for the OpenAI API wire format.

These models define the exact request and response shapes for OpenAI-compatible
endpoints. They must match the real OpenAI API specification so that existing
OpenAI client libraries (openai-python, openai-node, etc.) work seamlessly.

Reference: https://platform.openai.com/docs/api-reference/chat/create
"""

from __future__ import annotations

import time
from typing import Literal

from pydantic import BaseModel, Field


# =============================================================================
# Shared Sub-Models
# =============================================================================


class Usage(BaseModel):
    """Token usage statistics."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


# =============================================================================
# Chat Completion Request
# =============================================================================


class ChatMessageContent(BaseModel):
    """A single message in the chat conversation."""

    role: Literal["system", "user", "assistant"] = Field(
        ..., description="The role of the message author."
    )
    content: str = Field(
        ..., description="The text content of the message."
    )


class ChatCompletionRequest(BaseModel):
    """OpenAI Chat Completion request body.

    Reference: https://platform.openai.com/docs/api-reference/chat/create
    """

    model: str = Field(
        ..., description="ID of the model to use (e.g., 'gpt-4.1')."
    )
    messages: list[ChatMessageContent] = Field(
        ..., description="A list of messages comprising the conversation."
    )
    stream: bool = Field(
        default=False,
        description="If true, partial message deltas will be sent as SSE events.",
    )
    temperature: float = Field(
        default=1.0,
        ge=0.0,
        le=2.0,
        description="Sampling temperature between 0 and 2.",
    )
    max_tokens: int | None = Field(
        default=None,
        gt=0,
        description="Maximum number of tokens to generate.",
    )
    top_p: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Nucleus sampling parameter.",
    )
    stop: str | list[str] | None = Field(
        default=None,
        description="Sequences where the API will stop generating.",
    )
    frequency_penalty: float = Field(
        default=0.0,
        ge=-2.0,
        le=2.0,
        description="Penalize new tokens based on their frequency in the text so far.",
    )
    presence_penalty: float = Field(
        default=0.0,
        ge=-2.0,
        le=2.0,
        description="Penalize new tokens based on whether they appear in the text so far.",
    )
    n: int = Field(
        default=1,
        ge=1,
        le=1,
        description="Number of completions to generate. Only 1 is supported.",
    )
    user: str | None = Field(
        default=None,
        description="A unique identifier representing the end-user.",
    )


# =============================================================================
# Chat Completion Response (Non-Streaming)
# =============================================================================


class ChoiceMessage(BaseModel):
    """The message generated by the model."""

    role: Literal["assistant"] = "assistant"
    content: str = Field(..., description="The generated text content.")


class Choice(BaseModel):
    """A single completion choice."""

    index: int = 0
    message: ChoiceMessage
    finish_reason: Literal["stop", "length"] | None = "stop"


class ChatCompletionResponse(BaseModel):
    """OpenAI Chat Completion response body.

    Reference: https://platform.openai.com/docs/api-reference/chat/object
    """

    id: str = Field(..., description="Unique identifier for this completion.")
    object: Literal["chat.completion"] = "chat.completion"
    created: int = Field(
        default_factory=lambda: int(time.time()),
        description="Unix timestamp of when the completion was created.",
    )
    model: str = Field(..., description="The model used for this completion.")
    choices: list[Choice] = Field(
        ..., description="A list of completion choices."
    )
    usage: Usage = Field(
        default_factory=Usage,
        description="Token usage statistics for this request.",
    )


# =============================================================================
# Chat Completion Streaming (Chunks)
# =============================================================================


class DeltaContent(BaseModel):
    """Incremental content in a streaming chunk.

    On the first chunk, 'role' is set to 'assistant' and 'content' may be empty.
    On subsequent chunks, 'role' is omitted and 'content' contains the new text.
    On the final chunk, 'content' is omitted and only finish_reason is set.
    """

    role: Literal["assistant"] | None = None
    content: str | None = None


class ChunkChoice(BaseModel):
    """A single choice within a streaming chunk."""

    index: int = 0
    delta: DeltaContent
    finish_reason: Literal["stop", "length"] | None = None


class ChatCompletionChunk(BaseModel):
    """OpenAI Chat Completion streaming chunk.

    Sent as SSE events in the format: "data: {json}\\n\\n"
    Stream is terminated with: "data: [DONE]\\n\\n"
    """

    id: str = Field(..., description="Unique identifier (same across all chunks).")
    object: Literal["chat.completion.chunk"] = "chat.completion.chunk"
    created: int = Field(
        default_factory=lambda: int(time.time()),
        description="Unix timestamp of when the chunk was created.",
    )
    model: str = Field(..., description="The model generating this stream.")
    choices: list[ChunkChoice] = Field(
        ..., description="A list of chunk choices."
    )


# =============================================================================
# Models Endpoint
# =============================================================================


class ModelObject(BaseModel):
    """A single model in the models list.

    Reference: https://platform.openai.com/docs/api-reference/models/object
    """

    id: str = Field(..., description="The model identifier.")
    object: Literal["model"] = "model"
    created: int = Field(
        default_factory=lambda: int(time.time()),
        description="Unix timestamp of when the model was created.",
    )
    owned_by: str = Field(
        default="copilot",
        description="The organization that owns the model.",
    )


class ModelList(BaseModel):
    """OpenAI Models list response.

    Reference: https://platform.openai.com/docs/api-reference/models/list
    """

    object: Literal["list"] = "list"
    data: list[ModelObject] = Field(
        ..., description="A list of available model objects."
    )


# =============================================================================
# Error Response
# =============================================================================


class ErrorDetail(BaseModel):
    """OpenAI error detail object."""

    message: str = Field(..., description="Human-readable error message.")
    type: str = Field(..., description="Error type identifier.")
    code: str | None = Field(
        default=None, description="Machine-readable error code."
    )
    param: str | None = Field(
        default=None, description="The parameter that caused the error."
    )


class ErrorResponse(BaseModel):
    """OpenAI error response wrapper.

    All error responses follow this format:
    {"error": {"message": "...", "type": "...", "code": "..."}}
    """

    error: ErrorDetail
